[package]
name = "databind"
version = "0.1.0"
authors = ["Adam Thompson-Sharpe <adamthompsonsharpe@gmail.com>"]
edition = "2018"
description = "Expand the functionality of Minecraft Datapacks."
documentation = "https://databind.readthedocs.io/en/latest/"
readme = "README.md"
repository = "https://github.com/MysteryBlokHed/databind"
license = "MIT OR Apache-2.0"
keywords = ["minecraft", "datapacks"]
categories = ["compilers"]
exclude = [".github", ".vscode", "docs", "databind.toml"]

[dependencies]
clap = "2.33"
glob = "0.3"
rand = "0.8"
walkdir = "2.3"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
same-file = "1.0"
