# Add random characters to var names. Experimental
random_var_names = false
# Change the display name of randomized vars
var_display_names = false
# Whether to auto-generate function JSON in minecraft/tags/functions
generate_func_json = true
# Functions not to generate JSON for
func_json_exclusions = []
# Files to transpile
to_transpile = ["**/*.databind"]
