name: Build And Test
on:
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - tests/**
  push:
    branches:
      - master
    paths:
      - src/**
      - tests/**

jobs:
  windows_build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --all-features

      - name: Test
        run: cargo test --release --all-features

      - name: Upload release binary
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: ./target/release/databind.exe

  macos_build:
    name: macOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --all-features

      - name: Test
        run: cargo test --release --all-features

      - name: Upload release binary
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: ./target/release/databind

  ubuntu_build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --all-features

      - name: Test
        run: cargo test --release --all-features

      - name: Upload release binary
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: ./target/release/databind
