name: Build Docs
on:
  - push
  - pull_request

jobs:
  test_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: docs/
