name: Build Docs
on:
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  test_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: docs/
