name: Build, Test & Upload
on:
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - tests/**
      - Cargo.*
  push:
    branches:
      - master
    paths:
      - src/**
      - tests/**
      - Cargo.*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        include:
          - os: windows
            name: win
            bin: databind.exe

          - os: macos
            name: mac
            bin: databind

          - os: ubuntu
            name: linux
            bin: databind
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release --all-features --locked

      - name: Test
        run: cargo test --release --all-features --locked

      - name: Upload release binary
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}-build
          path: ./target/release/${{ matrix.bin }}
          if-no-files-found: error
