name: Build Docs
on:
  pull_request:
    branches:
      - master
    paths:
      - docs/**
  push:
    branches:
      - master
    paths:
      - docs/**

jobs:
  build_docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build Docs
        uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: docs/
