name: Add Binaries to Release
on:
  release:
    types: [published]

jobs:
  add_binaries:
    name: Add Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download release binaries
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_and_test.yaml
          workflow_conclusion: success
          path: ./binaries

      - name: Add Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./binaries/windows-build/databind.exe
          asset_name: databind-win.exe
          asset_content_type: application/octet-stream

      - name: Add macOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./binaries/macos-build/databind
          asset_name: databind-mac
          asset_content_type: application/octet-stream

      - name: Add Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./binaries/linux-build/databind
          asset_name: databind-linux
          asset_content_type: application/octet-stream
