name: Build And Test
on:
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - tests/**
  push:
    branches:
      - master
    paths:
      - src/**
      - tests/**

jobs:
  windows_build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --all-features

      - name: Test
        run: cargo test --all-features

  macos_build:
    name: macOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --all-features

      - name: Test
        run: cargo test --all-features

  ubuntu_build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --all-features

      - name: Test
        run: cargo test --all-features
