name: Build & Test
on:
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - tests/**
      - Cargo.*
  push:
    branches:
      - master
    paths:
      - src/**
      - tests/**
      - Cargo.*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    env:
      BIN_PATH: target/release/databind

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release --all-features --locked

      - name: Test
        run: cargo test --release --all-features --locked

      - if: ${{ matrix.os == 'windows-latest' }}
        name: Set Binary Path
        run: Write-Output 'BIN_PATH=target/release/databind.exe' >> $env:GITHUB_ENV

      - name: Upload release binary
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-build
          path: ${{ env.BIN_PATH }}
          if-no-files-found: error
