name: PR License Check
on:
  pull_request:
    branches:
      - master
    paths:
      - '**/*.rs'
      - README.md
      - docs/conf.py

jobs:
  check_license:
    name: Check License
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Check License
        uses: kt3k/license_checker@v1.0.6
